export declare namespace NotificationEventDto {
  enum TypeEnum {
    USERWELCOME = 'USERWELCOME',
    VERIFICATIONREQUEST = 'VERIFICATIONREQUEST',
    CONFIRMACCOUNT = 'CONFIRMACCOUNT',
    PASSWORDRESET = 'PASSWORDRESET',
    TRANSACTIONREQUEST = 'TRANSACTIONREQUEST',
    TRANSACTIONINVITE = 'TRANSACTIONINVITE',
    TRANSACTIONRECEIPTBUYER = 'TRANSACTIONRECEIPTBUYER',
    TRANSACTIONRECEIPTSELLER = 'TRANSACTIONRECEIPTSELLER',
    TRANSACTIONMILESTONERECEIPTBUYER = 'TRANSACTIONMILESTONERECEIPTBUYER',
    TRANSACTIONMILESTONERECEIPTSELLER = 'TRANSACTIONMILESTONERECEIPTSELLER',
    TRANSACTIONCOMPLETE = 'TRANSACTIONCOMPLETE',
    TRANSACTIONACCEPTED = 'TRANSACTIONACCEPTED',
    TRANSACTIONDECLINED = 'TRANSACTIONDECLINED',
    PAYMENTACTIONCODE = 'PAYMENTACTIONCODE',
    PAYMENTDISPUTE = 'PAYMENTDISPUTE',
    PAYMENTCONFIRMBUYER = 'PAYMENTCONFIRMBUYER',
    PAYMENTCONFIRMSELLER = 'PAYMENTCONFIRMSELLER',
  }

  enum UserTypeEnum {
    CANDIDATE = 'CANDIDATE',
    CLIENTUSER = 'CLIENTUSER',
  }
}
