name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Run test
        env:
            GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_TOKEN }}
            GITHUB_OWNER: distinctai
        run: |
          echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" >> $HOME/.npmrc && \
          npm config set @${GITHUB_OWNER}:registry https://npm.pkg.github.com/${GITHUB_OWNER}
          npm install
          npm run lint
          npm test
          npm run build
